name: $(RiseVocab.Version)-alpha.$(Rev:r)

variables:
  - group: RiseVocab.Common.Configurations
  - group: RiseVocab.Dev.Configurations
  - group: RiseVocab.DictionaryService.Configurations
  - name: RiseVocab.Version
    value: 0.0.0

trigger:
  - master

pr: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    command: login
    containerRegistry: $(RiseVocab.ContainerRegistryConnection)
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    dockerFile: dockerfile
    repository: $(RiseVocab.ProjectName)/$(RiseVocab.AppName)
    tags: |
     latest
     $(Build.BuildNumber)
- task: Docker@2
  displayName: Logout of Container Registry
  inputs:
    command: logout
    containerRegistry: $(RiseVocab.ContainerRegistryConnection)
